### ISSUE TITLE
Custom domain has expired

### ISSUE THREAD

**Issue by enamchae** [stogacs/website#9] opened 2021-04-08 04:26 UTC
The custom domain expired at the end of March so the website seems to be inaccessible. Don't know if we'd want to renew it yet or otherwise reopen the site at github.io for now.

**Comment by tujson** [comment] 2021-05-09 00:45
@bchiu42 is the current owner.

Feel free to transfer the domain back to me and I can take care of it for a bit.

**Comment by mirryi** [comment] 2021-05-09 20:28
Is @bchiu42 the currently one paying for the domain each year?

**Comment by tujson** [comment] 2021-05-09 20:41
> Is @bchiu42 the currently one paying for the domain each year?

To my knowledge, yes. I transferred it to him in March 2019.

**Comment by bchiu42** [comment] 2021-05-13 18:10
Hey guys,

As Jason said, I was the previous owner. I missed the renewal date. Sorry for missing it, I didn't check my Gmail often during the semester so I didn't realize it wasn't going to auto-renew. I paid for it a couple of days ago, but I am not sure how to link the files on the Github to the domain on Namecheap. I can transfer the ownership to anyone, or I can spend some time this weekend to figure it out. It makes no difference to me so tell me what you want.

Thanks,
Ben

P.S.
I am coming back to Philly this weekend so if any of you have time and are vaccinated we should meet up!
________________________________

**Comment by mirryi** [comment] 2021-05-13 20:11
It probably doesn't make sense to have you hanging on to that, so I think it would be a good idea to transfer it to someone who is going to be in the club next year. I'll see if anyone in the execs board is willing to manage it.

**Comment by tujson** [comment] 2021-06-22 16:58
Saw the domain expired. Repurchased and reconfigured. Confirmed working.

Any ideas on how to do this moving forward?
1. I can just hold onto it. Would appreciate an update every year or every few years in case the domain is no longer needed.
2. Have the acting president own the domain. <- Not a great plan since it creates a failure point every year.
3. ???

**Comment by mirryi** [comment] 2021-06-22 18:42
Accidental misclick on the close/reopen.

> Saw the domain expired. Repurchased and reconfigured. Confirmed working.
> 
> Any ideas on how to do this moving forward?
> 
> 1. I can just hold onto it. Would appreciate an update every year or every few years in case the domain is no longer needed.
> 2. Have the acting president own the domain. <- Not a great plan since it creates a failure point every year.
> 3. ???

True enough on the second point. If you're willing to hold on to it for now, (1) is probably the best way to proceed.

**Comment by tujson** [comment] 2021-06-22 19:18
Copy. Resolving ticket.

**Closed as completed** 2021-06-22 19:18 UTC
